// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SpecialityController from "./speciality_controller"
application.register("speciality", SpecialityController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TableController from "./table_controller"
application.register("table", TableController)

import TurboController from "./turbo_controller"
application.register("turbo", TurboController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
